/* @pjs preload=
"img/bg.jpg,
img/cabbage.png,
img/title.jpg,
img/gameover.jpg,
img/startNormal.png,
img/startHovered.png,
img/restartNormal.png,
img/restartHovered.png,
img/groundhogDown.png,
img/groundhogIdle.png,
img/groundhogLeft.png,
img/groundhogRight.png,
img/life.png,
img/soil.png,
img/soldier.png"; */